"""Prepare dataset and launch LLaMA-Factory LoRA training for InternVL multimodal model."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def normalize_dataset(input_path: Path, output_path: Path) -> int:
    raw = json.loads(input_path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError("dataset must be a JSON list")

    cleaned: list[dict] = []
    for row in raw:
        if not isinstance(row, dict):
            continue
        messages = row.get("messages")
        images = row.get("images")
        if not isinstance(messages, list) or len(messages) < 2:
            continue
        if not isinstance(images, list) or not images:
            continue

        user_msg = str((messages[0] or {}).get("content", "")).strip()
        assistant_msg = str((messages[1] or {}).get("content", "")).strip()
        if not user_msg or not assistant_msg:
            continue
        if "<image>" not in user_msg:
            user_msg = f"<image>{user_msg}"

        image_path = Path(str(images[0]))
        if not image_path.is_absolute():
            image_path = (input_path.parent / image_path).resolve()

        cleaned.append(
            {
                "messages": [
                    {"role": "user", "content": user_msg},
                    {"role": "assistant", "content": assistant_msg},
                ],
                "images": [str(image_path)],
            }
        )

    output_path.write_text(json.dumps(cleaned, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(cleaned)


def update_dataset_info(dataset_info_path: Path, dataset_name: str, file_name: str) -> None:
    if dataset_info_path.exists():
        data = json.loads(dataset_info_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            data = {}
    else:
        data = {}

    data[dataset_name] = {
        "file_name": file_name,
        "formatting": "sharegpt",
        "columns": {"messages": "messages", "images": "images"},
    }
    dataset_info_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def build_train_yaml(
    yaml_path: Path,
    model_path: Path,
    dataset_dir: Path,
    dataset_name: str,
    output_dir: Path,
    template: str,
    max_samples: int,
    epochs: float,
) -> None:
    content = f"""### model
model_name_or_path: {model_path.as_posix()}

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: {dataset_name}
dataset_dir: {dataset_dir.as_posix()}
template: {template}
cutoff_len: 4096
max_samples: {max_samples}
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: {output_dir.as_posix()}
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: {epochs}
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
flash_attn: fa2

### eval
val_size: 0.03
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
"""
    yaml_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train InternVL LoRA with LLaMA-Factory")
    parser.add_argument("--dataset-json", default="avis_vision.json", help="Raw dataset JSON generated by annotator.py")
    parser.add_argument("--dataset-name", default="avis_vision_internvl", help="Dataset alias in dataset_info.json")
    parser.add_argument("--model-path", default="InternVL3_5-14B-HF", help="InternVL HF model dir")
    parser.add_argument("--template", default="internvl2_5", help="LLaMA-Factory template name")
    parser.add_argument("--output-dir", default="outputs/internvl14b_lora", help="LoRA output directory")
    parser.add_argument("--max-samples", type=int, default=200000)
    parser.add_argument("--epochs", type=float, default=3.0)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent
    dataset_json = (base_dir / args.dataset_json).resolve()
    model_path = (base_dir / args.model_path).resolve()
    output_dir = (base_dir / args.output_dir).resolve()

    if not dataset_json.exists():
        raise FileNotFoundError(f"dataset not found: {dataset_json}")
    if not model_path.exists():
        raise FileNotFoundError(f"model path not found: {model_path}")

    normalized_name = f"{args.dataset_name}.json"
    normalized_path = (base_dir / normalized_name).resolve()
    count = normalize_dataset(dataset_json, normalized_path)
    if count <= 0:
        raise RuntimeError("no valid samples found after normalization")

    dataset_info_path = base_dir / "dataset_info.json"
    update_dataset_info(dataset_info_path, args.dataset_name, normalized_name)

    train_yaml = base_dir / "train_internvl_lora.generated.yaml"
    build_train_yaml(
        yaml_path=train_yaml,
        model_path=model_path,
        dataset_dir=base_dir,
        dataset_name=args.dataset_name,
        output_dir=output_dir,
        template=args.template,
        max_samples=max(1, args.max_samples),
        epochs=max(0.1, args.epochs),
    )

    print(f"prepared samples: {count}")
    print(f"normalized dataset: {normalized_path}")
    print(f"dataset info: {dataset_info_path}")
    print(f"train yaml: {train_yaml}")

    if args.dry_run:
        print("dry-run enabled: skip training launch")
        return

    cmd = ["llamafactory-cli", "train", str(train_yaml)]
    print("running:", " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=str(base_dir))


if __name__ == "__main__":
    main()
